name: C/C++ CI

on:
  push:
    branches: [ master, dev, sdl2 ]
  pull_request:
    branches: [ master, sdl2 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install build dependencies
      run: sudo apt-get install libsdl1.2-dev libsdl-mixer1.2-dev libsdl-image1.2-dev libpng-dev
  
    - name: Configure project
      run: |
        mkdir $GITHUB_WORKSPACE/build
        cd $GITHUB_WORKSPACE/build
        cmake ..

    - name: Run make
      run: |
        cd $GITHUB_WORKSPACE/build
        make
